import type { Project } from '~/models/interfaces/projects'

export const projectExample1: Project = {
  bids: [
    {
      adId: 16,
      amount: 50,
      createdAt: new Date('2024-10-24 09:17:24'),
      createdBy: 1,
      currency: 'USD',
      deletedAt: null,
      deletedBy: null,
      deliveryDays: 0,
      description: 'Estoy corrigiendo la descripcion de la propuesta',
      id: 2,
      options: null,
      organizationId: null,
      selected: 1,
      statusId: 0,
      statusLabel: {
        title: 'Pendiente',
      },
      updatedAt: new Date('2024-10-24 09:46:59'),
      updatedBy: 1,
    },
    {
      adId: 16,
      amount: 150,
      createdAt: new Date('2024-10-24 09:26:03'),
      createdBy: 1,
      currency: 'USD',
      deletedAt: null,
      deletedBy: null,
      deliveryDays: 5,
      description: 'Esta es una descripcion de la propuesta',
      id: 3,
      options: null,
      organizationId: null,
      selected: 0,
      statusId: 0,
      statusLabel: {
        title: 'Pendiente',
      },
      updatedAt: new Date('2024-10-24 09:46:59'),
      updatedBy: 1,
    },
    {
      adId: 16,
      amount: 200,
      createdAt: new Date('2024-10-24 15:30:23'),
      createdBy: 1,
      currency: 'USD',
      deletedAt: null,
      deletedBy: null,
      deliveryDays: 5,
      description: 'Esta es una descripcion de la propuesta XN',
      id: 5,
      options: null,
      organizationId: null,
      selected: 0,
      statusId: 0,
      statusLabel: {
        title: 'Pendiente',
      },
      updatedAt: new Date('2024-10-24 15:30:23'),
      updatedBy: 1,
    },
  ],
  categories: [
    {
      createdAt: new Date('2024-10-21 11:46:41'),
      createdBy: 1,
      deletedAt: null,
      deletedBy: null,
      depth: null,
      description: '<p>Python</p>',
      id: 38,
      lft: 29,
      options: null,
      organizationId: null,
      parentId: 6,
      pivot: {
        adId: 16,
        categoryId: 38,
      },
      rgt: 30,
      slug: 'python',
      sortOrder: 0,
      status: 1,
      title: 'Python',
      updatedAt: new Date('2024-10-21 11:46:41'),
      updatedBy: 1,
      url: 'https://dev-clustertic.ozonohosting.com/anuncios/c/python',
    },
    {
      createdAt: new Date('2024-10-21 11:47:00'),
      createdBy: 1,
      deletedAt: null,
      deletedBy: null,
      depth: null,
      description: '<p>Bash</p>',
      id: 39,
      lft: 31,
      options: null,
      organizationId: null,
      parentId: 6,
      pivot: {
        adId: 16,
        categoryId: 39,
      },
      rgt: 32,
      slug: 'bash',
      sortOrder: 0,
      status: 1,
      title: 'Bash',
      updatedAt: new Date('2024-10-21 11:47:00'),
      updatedBy: 1,
      url: 'https://dev-clustertic.ozonohosting.com/anuncios/c/bash',
    },
  ],
  checked: '0',
  cityId: 1,
  countryId: 48,
  createdAt: new Date('2024-10-23 15:39:02'),
  createdBy: 1,
  defaultPrice: 100,
  deletedAt: null,
  deletedBy: null,
  description: 'Esta es la descripcion',
  entityTitle: 'Test entity name',
  featured: 0,
  fields: [],
  files: [
    {
      id: 9,
      filename: 'slider-test-3.png',
      mimeType: 'image/png',
      fileSize: '155085',
      path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3.png?u=1730843147',
      relativePath: '/assets/media/slider-test-3.png',
      isImage: true,
      isVideo: false,
      isFolder: false,
      mediaType: 'image',
      folderId: '0',
      description: null,
      alt: null,
      keywords: null,
      createdBy: 1,
      createdAt: new Date('2024-10-23 14:53:51'),
      updatedAt: new Date('2024-11-05 16:45:47'),
      faIcon: 'fa-file',
      disk: 's3',
      extension: 'png',
      zone: 'gallery',
      url: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3.png',
      tags: [],
      thumbnails: [
        {
          name: 'smallThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_smallThumb.webp',
          size: '300x',
        },
        {
          name: 'mediumThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_mediumThumb.webp',
          size: '600x',
        },
        {
          name: 'largeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_largeThumb.webp',
          size: '900x',
        },
        {
          name: 'extraLargeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_extraLargeThumb.webp',
          size: '1920x',
        },
      ],
      smallThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_smallThumb.webp',
      relativeSmallThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_smallThumb.webp',
      mediumThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_mediumThumb.webp',
      relativeMediumThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_mediumThumb.webp',
      largeThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_largeThumb.webp',
      relativeLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_largeThumb.webp',
      extraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_extraLargeThumb.webp',
      relativeExtraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_extraLargeThumb.webp',
    },
  ],
  id: 16,
  lat: null,
  lng: null,
  maxPrice: 250,
  mediaFiles: {
    mainimage: {
      id: null,
      filename: null,
      mimeType: null,
      fileSize: null,
      path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativePath: 'modules/media/img/file/default.jpg',
      isImage: true,
      isVideo: false,
      isFolder: false,
      mediaType: '',
      folderId: null,
      description: null,
      alt: null,
      keywords: null,
      createdBy: null,
      createdAt: null,
      updatedAt: null,
      faIcon: 'fa-file',
      disk: null,
      extension: null,
      url: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg',
      tags: [],
      thumbnails: [
        {
          name: 'smallThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '300x',
        },
        {
          name: 'mediumThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '600x',
        },
        {
          name: 'largeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '900x',
        },
        {
          name: 'extraLargeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '1920x',
        },
      ],
      smallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeSmallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      mediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeMediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      largeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      extraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeExtraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
    },
    secondaryimage: {
      id: null,
      filename: null,
      mimeType: null,
      fileSize: null,
      path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativePath: 'modules/media/img/file/default.jpg',
      isImage: true,
      isVideo: false,
      isFolder: false,
      mediaType: '',
      folderId: null,
      description: null,
      alt: null,
      keywords: null,
      createdBy: null,
      createdAt: null,
      updatedAt: null,
      faIcon: 'fa-file',
      disk: null,
      extension: null,
      url: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg',
      tags: [],
      thumbnails: [
        {
          name: 'smallThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '300x',
        },
        {
          name: 'mediumThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '600x',
        },
        {
          name: 'largeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '900x',
        },
        {
          name: 'extraLargeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '1920x',
        },
      ],
      smallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeSmallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      mediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeMediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      largeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      extraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeExtraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
    },
    gallery: [
      {
        id: 9,
        filename: 'slider-test-3.png',
        mimeType: 'image/png',
        fileSize: '155085',
        path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3.png?u=1730843147',
        relativePath: '/assets/media/slider-test-3.png',
        isImage: true,
        isVideo: false,
        isFolder: false,
        mediaType: 'image',
        folderId: '0',
        description: null,
        alt: null,
        keywords: null,
        createdBy: 1,
        createdAt: new Date('2024-10-23 14:53:51'),
        updatedAt: new Date('2024-11-05 16:45:47'),
        faIcon: 'fa-file',
        disk: 's3',
        extension: 'png',
        zone: 'gallery',
        url: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3.png',
        tags: [],
        thumbnails: [
          {
            name: 'smallThumb',
            path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_smallThumb.webp',
            size: '300x',
          },
          {
            name: 'mediumThumb',
            path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_mediumThumb.webp',
            size: '600x',
          },
          {
            name: 'largeThumb',
            path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_largeThumb.webp',
            size: '900x',
          },
          {
            name: 'extraLargeThumb',
            path: 'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_extraLargeThumb.webp',
            size: '1920x',
          },
        ],
        smallThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_smallThumb.webp',
        relativeSmallThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_smallThumb.webp',
        mediumThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_mediumThumb.webp',
        relativeMediumThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_mediumThumb.webp',
        largeThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_largeThumb.webp',
        relativeLargeThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_largeThumb.webp',
        extraLargeThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_extraLargeThumb.webp',
        relativeExtraLargeThumb:
          'https://s3.wasabisys.com/assets.cluster/assets/media/slider-test-3_extraLargeThumb.webp',
      },
    ],
    videos: [],
  },
  mediasMulti: {
    gallery: {
      files: [9],
    },
    videos: {
      files: [],
    },
  },
  mediasSingle: [],
  minPrice: 100,
  neighborhoodId: null,
  options: null,
  organizationId: null,
  provinceId: 694,
  slug: 'proyecto-5',
  sortOrder: 0,
  status: 2,
  statusName: 'Publicado',
  title: 'Proyecto 5',
  updatedAt: new Date('2024-10-23 15:39:02'),
  updatedBy: 1,
  uploadedAt: new Date('2024-10-23 20:39:02'),
  url: 'https://dev-clustertic.ozonohosting.com/anuncios/proyecto-5',
  user: {
    createdAt: new Date('2024-06-18 18:24:24'),
    createdBy: 1,
    deletedAt: null,
    deletedBy: null,
    email: 'soporte@imaginacolombia.com',
    firstName: 'Imagina',
    id: 1,
    isGuest: 0,
    language: null,
    lastLogin: new Date('2024-11-07 11:20:11'),
    lastName: 'Colombia',
    organizationId: null,
    permissions: [],
    phone: '57null',
    timezone: null,
    updatedAt: new Date('2024-11-07 11:20:11'),
    updatedBy: 1,
    userName: null,
  },
  userId: 1,
}
