import type { Project } from '~/models/interfaces/projects'

export const projectExample1: Project = {
  bids: [],
  categories: [],
  checked: '0',
  cityId: 1,
  countryId: 48,
  createdAt: '2024-10-23 15:39:02',
  createdBy: 1,
  defaultPrice: 100,
  deletedAt: null,
  deletedBy: null,
  description: '',
  entityTitle: '',
  featured: 0,
  fields: [],
  files: [],
  id: 16,
  lat: null,
  lng: null,
  maxPrice: 250,
  mediaFiles: {
    mainimage: {
      id: null,
      filename: null,
      mimeType: null,
      fileSize: null,
      path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativePath: 'modules/media/img/file/default.jpg',
      isImage: true,
      isVideo: false,
      isFolder: false,
      mediaType: '',
      folderId: null,
      description: null,
      alt: null,
      keywords: null,
      createdBy: null,
      createdAt: null,
      updatedAt: null,
      faIcon: 'fa-file',
      disk: null,
      extension: null,
      url: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg',
      tags: [],
      thumbnails: [
        {
          name: 'smallThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '300x',
        },
        {
          name: 'mediumThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '600x',
        },
        {
          name: 'largeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '900x',
        },
        {
          name: 'extraLargeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '1920x',
        },
      ],
      smallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeSmallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      mediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeMediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      largeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      extraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeExtraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
    },
    secondaryimage: {
      id: null,
      filename: null,
      mimeType: null,
      fileSize: null,
      path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativePath: 'modules/media/img/file/default.jpg',
      isImage: true,
      isVideo: false,
      isFolder: false,
      mediaType: '',
      folderId: null,
      description: null,
      alt: null,
      keywords: null,
      createdBy: null,
      createdAt: null,
      updatedAt: null,
      faIcon: 'fa-file',
      disk: null,
      extension: null,
      url: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg',
      tags: [],
      thumbnails: [
        {
          name: 'smallThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '300x',
        },
        {
          name: 'mediumThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '600x',
        },
        {
          name: 'largeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '900x',
        },
        {
          name: 'extraLargeThumb',
          path: 'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
          size: '1920x',
        },
      ],
      smallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeSmallThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      mediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeMediumThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      largeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      extraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
      relativeExtraLargeThumb:
        'https://s3.wasabisys.com/assets.cluster/modules/media/img/file/default.jpg?u=',
    },
    gallery: [],
    videos: [],
  },
  mediasMulti: {
    gallery: {
      files: [9],
    },
    videos: {
      files: [],
    },
  },
  mediasSingle: [],
  minPrice: 100,
  neighborhoodId: null,
  options: null,
  organizationId: null,
  provinceId: 694,
  slug: 'proyecto-5',
  sortOrder: 0,
  status: 2,
  statusName: 'Publicado',
  title: 'Proyecto 5',
  updatedAt: '2024-10-23 15:39:02',
  updatedBy: 1,
  uploadedAt: '2024-10-23 20:39:02',
  url: 'https://dev-clustertic.ozonohosting.com/anuncios/proyecto-5',
  user: {
    createdAt: '2024-06-18 18:24:24',
    createdBy: 1,
    deletedAt: null,
    deletedBy: null,
    email: '',
    firstName: '',
    id: 1,
    isGuest: 0,
    language: null,
    lastLogin: '2024-11-07 11:20:11',
    lastName: '',
    organizationId: null,
    permissions: [],
    phone: '',
    timezone: null,
    updatedAt: '2024-11-07 11:20:11',
    updatedBy: 1,
    userName: null,
  },
  userId: 1,
}
