export { default as Card } from './Card.vue'
export { default as CardHeader } from './CardHeader.vue'
export { default as CardTitle } from './CardTitle.vue'
export { default as CardDescription } from './CardDescription.vue'
export { default as CardContent } from './CardContent.vue'
export { default as CardFooter } from './CardFooter.vue'

export { default as CardProject } from './layouts/CardProject.vue'
export { default as CardProposal } from './layouts/CardProposal.vue'
export { default as CardPortfolio } from './layouts/CardPortfolio.vue'
export { default as CardExperience } from './layouts/CardExperience.vue'
export { default as CardSmallProfile } from './layouts/CardSmallProfile.vue'
