// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/19/2024, 9:06:59 AM
const configMerger = require("/Users/wilmer/Desktop/imagina/base-nuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/wilmer/Desktop/imagina/base-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilmer/Desktop/imagina/base-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilmer/Desktop/imagina/base-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilmer/Desktop/imagina/base-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilmer/Desktop/imagina/base-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wilmer/Desktop/imagina/base-nuxt/plugins/**/*.{js,ts,mjs}","/Users/wilmer/Desktop/imagina/base-nuxt/composables/**/*.{js,ts,mjs}","/Users/wilmer/Desktop/imagina/base-nuxt/utils/**/*.{js,ts,mjs}","/Users/wilmer/Desktop/imagina/base-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/wilmer/Desktop/imagina/base-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/wilmer/Desktop/imagina/base-nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
